[libraries]
surf.files = [
    "./submodules/surf/**/*.vhd"
]
# Must exclude build dir as vhdl files are mirrored to this directory when
# running GHDL (including cocotb) simulations for surf.
surf.exclude= [
    "./submodules/surf/build/**/*.vhd"
]

axi_soc_ultra_plus_core.files = [
    "./submodules/axi-soc-ultra-plus-core/shared/rtl/*.vhd",
    "./submodules/axi-soc-ultra-plus-core/shared/rfsoc-utility/**/rtl/*.vhd"
]

top.files = [
    "./targets/KekLrspBpmBt/hdl/KekLrspBpmBt.vhd",
    "./shared/rtl/*.vhd"
]

unisim.files = [
    '$XILINX_VIVADO/data/vhdl/src/unisims/unisim_VCOMP.vhd',
    '$XILINX_VIVADO/data/vhdl/src/unisims/primitive/*.vhd*',
]

[lint]
unnecessary_work_library = false # Disable linting for the 'library work;' statement
